# Exported from Render on 2026-07-17T19:33:17Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: task-manager-backend
      runtime: docker
      repo: https://github.com/yashparashar02/task-manager-app
      plan: free
      envVars:
      - key: DB_PASSWORD
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_URL
        sync: false
      region: singapore
      dockerContext: .
      dockerfilePath: ./Dockerfile
      autoDeployTrigger: commit
      rootDir: backend